CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE BOOKPUBLISH (
    BookID INT,
    Title VARCHAR(100),
    AuthorID INT,
    AuthorName VARCHAR(50),
    ISBN VARCHAR(20),
    Publisher VARCHAR(100),
    PublicationYear INT,
    Pages INT,
    Language VARCHAR(50),
    CopiesAvailable INT
);

CREATE TABLE MEMBERS (
    MemberID INT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    Address VARCHAR(255),
    City VARCHAR(50),
    State VARCHAR(50),
    ZipCode VARCHAR(10),
    JoinDate DATE
);

CREATE TABLE PUBLISHERS (
    PublisherID INT,
    PublisherName VARCHAR(100),
    ContactName VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    Address VARCHAR(255),
    City VARCHAR(50),
    State VARCHAR(50),
    ZipCode VARCHAR(10),
    Country VARCHAR(50)
);

CREATE TABLE STAFF (
    StaffID INT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    JobTitle VARCHAR(50),
    Department VARCHAR(50),
    HireDate DATE,
    Salary DECIMAL(10,2),
    Status VARCHAR(20)
);

CREATE TABLE SUPPLIERS (
    SupplierID INT,
    SupplierName VARCHAR(100),
    ContactName VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    Address VARCHAR(255),
    Country VARCHAR(50),
    Website VARCHAR(100),
    PaymentTerms VARCHAR(50),
    Rating INT
);



ALTER TABLE BOOKPUBLISH ADD Edition VARCHAR(50);
ALTER TABLE BOOKPUBLISH ADD ShelfLocation VARCHAR(50);
ALTER TABLE BOOKPUBLISH ADD BookCondition VARCHAR(50);
ALTER TABLE BOOKPUBLISH ADD Price DECIMAL(8,2);

ALTER TABLE MEMBERS ADD DateOfBirth DATE;
ALTER TABLE MEMBERS ADD MembershipType VARCHAR(50);
ALTER TABLE MEMBERS ADD Status VARCHAR(20);
ALTER TABLE MEMBERS ADD EmergencyContact VARCHAR(100);

ALTER TABLE PUBLISHERS ADD WebsiteURL VARCHAR(100);
ALTER TABLE PUBLISHERS ADD FoundedYear INT;
ALTER TABLE PUBLISHERS ADD CEOName VARCHAR(100);
ALTER TABLE PUBLISHERS ADD NoOfEmployees INT;

ALTER TABLE STAFF ADD ManagerID INT;
ALTER TABLE STAFF ADD EmergencyContact VARCHAR(100);
ALTER TABLE STAFF ADD BloodGroup VARCHAR(10);
ALTER TABLE STAFF ADD Shift VARCHAR(20);

ALTER TABLE SUPPLIERS ADD LicenseNumber VARCHAR(50);
ALTER TABLE SUPPLIERS ADD GSTNumber VARCHAR(50);
ALTER TABLE SUPPLIERS ADD BankAccount VARCHAR(50);
ALTER TABLE SUPPLIERS ADD ContractStart DATE;



ALTER TABLE BOOKPUBLISH DROP COLUMN ShelfLocation;
ALTER TABLE MEMBERS DROP COLUMN MembershipType;
ALTER TABLE PUBLISHERS DROP COLUMN NoOfEmployees;
ALTER TABLE STAFF DROP COLUMN EmergencyContact;
ALTER TABLE SUPPLIERS DROP COLUMN LicenseNumber;



ALTER TABLE BOOKPUBLISH RENAME COLUMN Title TO BookTitle;
ALTER TABLE BOOKPUBLISH RENAME COLUMN AuthorID TO WrittenBy;
ALTER TABLE BOOKPUBLISH RENAME COLUMN ISBN TO ISBNCode;
ALTER TABLE BOOKPUBLISH RENAME COLUMN Pages TO TotalPages;

ALTER TABLE MEMBERS RENAME COLUMN FirstName TO FName;
ALTER TABLE MEMBERS RENAME COLUMN LastName TO LName;
ALTER TABLE MEMBERS RENAME COLUMN Email TO EmailAddress;
ALTER TABLE MEMBERS RENAME COLUMN Phone TO ContactNumber;

ALTER TABLE PUBLISHERS RENAME COLUMN PublisherName TO Name;
ALTER TABLE PUBLISHERS RENAME COLUMN ContactName TO Representative;
ALTER TABLE PUBLISHERS RENAME COLUMN Email TO ContactEmail;
ALTER TABLE PUBLISHERS RENAME COLUMN Phone TO ContactNumber;

ALTER TABLE STAFF RENAME COLUMN FirstName TO FName;
ALTER TABLE STAFF RENAME COLUMN LastName TO LName;
ALTER TABLE STAFF RENAME COLUMN Email TO EmailAddress;
ALTER TABLE STAFF RENAME COLUMN Phone TO Mobile;

ALTER TABLE SUPPLIERS RENAME COLUMN SupplierName TO Name;
ALTER TABLE SUPPLIERS RENAME COLUMN ContactName TO Representative;
ALTER TABLE SUPPLIERS RENAME COLUMN Email TO ContactEmail;
ALTER TABLE SUPPLIERS RENAME COLUMN Phone TO ContactPhone;



ALTER TABLE BOOKPUBLISH MODIFY BookTitle VARCHAR(150);
ALTER TABLE BOOKPUBLISH MODIFY Publisher VARCHAR(150);
ALTER TABLE BOOKPUBLISH MODIFY ISBNCode VARCHAR(30);
ALTER TABLE BOOKPUBLISH MODIFY Price DECIMAL(10,2);

ALTER TABLE MEMBERS MODIFY FName VARCHAR(80);
ALTER TABLE MEMBERS MODIFY LName VARCHAR(80);
ALTER TABLE MEMBERS MODIFY EmailAddress VARCHAR(150);
ALTER TABLE MEMBERS MODIFY ContactNumber VARCHAR(30);

ALTER TABLE PUBLISHERS MODIFY Name VARCHAR(150);
ALTER TABLE PUBLISHERS MODIFY Representative VARCHAR(100);
ALTER TABLE PUBLISHERS MODIFY ContactEmail VARCHAR(150);
ALTER TABLE PUBLISHERS MODIFY ContactNumber VARCHAR(30);

ALTER TABLE STAFF MODIFY FName VARCHAR(80);
ALTER TABLE STAFF MODIFY LName VARCHAR(80);
ALTER TABLE STAFF MODIFY EmailAddress VARCHAR(150);
ALTER TABLE STAFF MODIFY Salary DECIMAL(12,2);

ALTER TABLE SUPPLIERS MODIFY Name VARCHAR(150);
ALTER TABLE SUPPLIERS MODIFY ContactEmail VARCHAR(150);
ALTER TABLE SUPPLIERS MODIFY ContactPhone VARCHAR(30);
ALTER TABLE SUPPLIERS MODIFY Rating INT;




